.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "UMPS3" "1" "August 2020" "" ""
.
.SH "NAME"
\fBumps3\fR \- Virtual machine simulator based around the MIPS R2/3000 microprocessor
.
.SH "SYNOPSIS"
\fBumps3\fR [\fICONFIGURATION\fR]
.
.SH "DESCRIPTION"
\fBuMPS\fR is an educational computer system architecture and an accompanying emulator designed from the ground up to achieve the right trade\-off between simplicity and elegance on one side, and realism on the other\. This makes \fBuMPS\fR ideally suited for use in education, such as hands\-on operating systems or computer architecture university courses\.
.
.P
The uMPS processor implements the MIPS I instruction set, and can therefore be supported out of the box by existing MIPS compilers\. The architecture details a complete set of I/O devices (terminals, disks, flash devices, printers, and network adapters) that feature a clean, consistent, programming interface\. The previous revision of the uMPS architecture (uMPS2) brings multiprocessor support\.
.
.P
The emulator comes with built\-in debugging features and an easy to use graphical user interface\. Apart from the emulator itself, several support utilities are provided that can get you quickly started in developing programs for \fBuMPS\fR\.
.
.SH "AUTHOR"
Mauro Morsiani
.
.br
Tomislav Jonjic \fItjonjic@gmail\.com\fR
.
.br
Mattia Biondi \fImattiabiondi1@gmail\.com\fR
.
.br
Contributors can be listed on GitHub\.
.
.SH "BUGS"
Report issues on GitHub: \fIhttps://github\.com/virtualsquare/umps3\fR
.
.SH "SEE ALSO"
\fBumps3\-elf2umps\fR(1), \fBumps3\-mkdev\fR(1), \fBumps3\-objdump\fR(1)
.
.P
Full documentation at: \fIhttps://github\.com/virtualsquare/umps3\fR
.
.br
Project wiki: \fIhttps://wiki\.virtualsquare\.org/#!umps/umps\.md\fR
.
.SH "COPYRIGHT"
2004, Mauro Morsiani
.
.br
2010\-2011, Tomislav Jonjic \fItjonjic@gmail\.com\fR
.
.br
2020, Mattia Biondi \fImattiabiondi1@gmail\.com\fR
