.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "UMPS3\-OBJDUMP" "1" "August 2020" "" ""
.
.SH "NAME"
\fBumps3\-objdump\fR \- The umps3\-objdump object file analysis utility
.
.SH "SYNOPSIS"
\fBumps3\-objdump\fR [\fIOPTIONS\fR] \fIFILE\fR
.
.SH "DESCRIPTION"
The command\-line \fBumps3\-objdump\fR utility is used to analyze object files created by the \fBumps3\-elf2umps\fR utility\.
.
.P
This utility performs the same functions as \fBmipsel\-linux\-gnu\-objdump\fR (or \fBmips\-linux\-gnu\-objdump\fR) which is included in the cross\-platform development tool set\.
.
.P
\fBumps3\-objdump\fR is used to analyze \fB\.core\fR, \fB\.rom\fR, and \fB\.aout\fR object files while \fBmipsel\-linux\-gnu\-objdump\fR is used to analyze ELF\-formatted object files\.
.
.P
The output from \fBumps3\-objdump\fR is directed to stdout\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR
Optional flag to show the \fB\.aout\fR program header, if present\.
.
.TP
\fB\-d\fR
Optional flag to "disassemble" and display the \fB\.text\fR area in \fIFILE\fR\.
.
.br
This is an "assembly" dump of the code, thus it will contain load and branch delay slots; differing from the machine language version of the same code\.
.
.TP
\fB\-x\fR
Optional flag to produce a complete little\-endian format hexadecimal word dump of \fIFILE\fR\.
.
.br
Zero\-filled blocks will be skipped and marked with *asterisks*\.
.
.br
The output will appear identical regardless of whether \fIFILE\fR is little\-endian or big\-endian\.
.
.TP
\fB\-b\fR
Optional flag to produce a complete byte dump of \fIFILE\fR\.
.
.br
Zero\-filled blocks will be skipped and marked with *asterisks*\.
.
.br
Unlike with the \fI\-x\fR flag, the endian\-format of the output will depend on the endianness of \fIFILE\fR; i\.e\. if \fIFILE\fR is big\-endian than the output will be big\-endian\.
.
.TP
\fB\-a\fR
Flag to perform all of the above optional operations\.
.
.SH "FILES"
\fIFILE\fR is the \fB\.core\fR, \fB\.rom\fR, or \fB\.aout\fR object file to be analyzed\.
.
.SH "AUTHOR"
Mauro Morsiani
.
.br
Contributors can be listed on GitHub\.
.
.SH "BUGS"
Report issues on GitHub: \fIhttps://github\.com/virtualsquare/umps3\fR
.
.SH "SEE ALSO"
\fBumps3\fR(1), \fBumps3\-elf2umps\fR(1), \fBumps3\-mkdev\fR(1)
.
.P
Full documentation at: \fIhttps://github\.com/virtualsquare/umps3\fR
.
.br
Project wiki: \fIhttps://wiki\.virtualsquare\.org/#!umps/umps\.md\fR
.
.SH "COPYRIGHT"
2004, Mauro Morsiani
.
.br

